services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_resume_builder_app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:8000"
    command:
      - watchmedo
      - auto-restart
      - --debug-force-polling
      - --interval=1
      - --directory=/var/www/html
      - --pattern=*.py
      - --
      - python
      - main.py
    environment:
      GRADIO_SERVER_NAME: "0.0.0.0"
      GRADIO_SERVER_PORT: "8000"
      PYTHONUNBUFFERED: "1"
    depends_on:
      - pg_vector
    networks:
      - localnet

  pg_vector:
    image: pgvector/pgvector:0.8.4-pg18-trixie
    container_name: pg_vector
    restart: unless-stopped
    ports:
      - "6024:5432"
    networks:
      - localnet
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  localnet:
    driver: bridge

volumes:
  pg_data:
